name = input("What's your name ? : ")
age = input("How old are you ? : ")
weight = int(input("Input your weight :"))
height = int(input("Input your height :"))
print("Hello", name)
print("Your age is ", age)
print("Your weight is", weight, "kg")
print("Your weight is %d kg" % weight)
print("Your weight is %d kg and height is %d cm." % (weight, height))
print("Your weight is {} kg and height is {} cm." .format(weight, height))
print(f'Your weight is {weight} kg and height is {height} cm.')
print("May be next year weight ", weight+10)
